language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
  - pip install coveralls
  - LC_ALL=C pip install .
script:
  - make check
  - coverage run --source=natsort setup.py test
after_success:
  coveralls
